export interface EmojiOption {
  symbol: string;
  label: string;
  keywords: string[];
}

export const emojiOptions: EmojiOption[] = [
  { symbol: "💰", label: "Savings", keywords: ["savings", "money", "cash", "wealth", "budget", "bank"] },
  { symbol: "💳", label: "Card Payment", keywords: ["card", "credit", "debit", "payment", "bill", "purchase"] },
  { symbol: "🏦", label: "Bank", keywords: ["bank", "finance", "institution", "vault"] },
  { symbol: "📈", label: "Investments", keywords: ["investment", "stocks", "growth", "returns", "portfolio"] },
  { symbol: "📉", label: "Losses", keywords: ["loss", "decline", "market", "investment"] },
  { symbol: "💹", label: "Trading", keywords: ["trading", "forex", "crypto", "stock", "market"] },
  { symbol: "🧾", label: "Bills", keywords: ["bills", "receipts", "invoice", "statement", "utilities"] },
  { symbol: "🛒", label: "Groceries", keywords: ["groceries", "shopping", "supermarket", "food"] },
  { symbol: "🍽️", label: "Dining Out", keywords: ["dining", "restaurant", "food", "meal", "eat"] },
  { symbol: "☕", label: "Coffee", keywords: ["coffee", "tea", "drink", "cafe"] },
  { symbol: "🍔", label: "Fast Food", keywords: ["burger", "fast", "food", "snack", "restaurant"] },
  { symbol: "🥗", label: "Healthy Food", keywords: ["healthy", "salad", "food", "meal", "diet"] },
  { symbol: "🎂", label: "Celebration", keywords: ["cake", "party", "celebration", "birthday", "event"] },
  { symbol: "🚗", label: "Car", keywords: ["car", "auto", "vehicle", "transport"] },
  { symbol: "🚕", label: "Taxi", keywords: ["taxi", "rideshare", "transport", "uber"] },
  { symbol: "🛵", label: "Motorbike", keywords: ["motorbike", "scooter", "ride", "transport"] },
  { symbol: "⛽", label: "Fuel", keywords: ["fuel", "gas", "petrol", "energy", "car"] },
  { symbol: "🛣️", label: "Toll & Parking", keywords: ["toll", "parking", "road", "transport"] },
  { symbol: "✈️", label: "Flights", keywords: ["flight", "travel", "plane", "trip"] },
  { symbol: "🧳", label: "Travel", keywords: ["travel", "vacation", "holiday", "trip", "tour"] },
  { symbol: "🏨", label: "Accommodation", keywords: ["hotel", "stay", "lodging", "travel"] },
  { symbol: "🛏️", label: "Home Stay", keywords: ["home", "stay", "bnb", "lodging"] },
  { symbol: "🏡", label: "Home", keywords: ["home", "mortgage", "rent", "housing", "property"] },
  { symbol: "🏠", label: "Rent", keywords: ["rent", "housing", "lease", "home"] },
  { symbol: "🛠️", label: "Repairs", keywords: ["repair", "maintenance", "fix", "service"] },
  { symbol: "🧹", label: "Cleaning", keywords: ["cleaning", "housework", "home", "maid"] },
  { symbol: "💡", label: "Utilities", keywords: ["utilities", "electricity", "light", "power", "energy", "bill"] },
  { symbol: "🚿", label: "Water", keywords: ["water", "utilities", "bill", "bath"] },
  { symbol: "🔥", label: "Heating", keywords: ["heat", "gas", "utilities", "energy"] },
  { symbol: "📦", label: "Subscriptions", keywords: ["subscription", "box", "delivery", "membership"] },
  { symbol: "💻", label: "Electronics", keywords: ["electronics", "computer", "tech", "hardware"] },
  { symbol: "📱", label: "Mobile", keywords: ["phone", "mobile", "cell", "device", "bill"] },
  { symbol: "🖥️", label: "Software", keywords: ["software", "apps", "subscription", "digital"] },
  { symbol: "🎮", label: "Gaming", keywords: ["gaming", "games", "console", "fun"] },
  { symbol: "🎧", label: "Music", keywords: ["music", "audio", "subscription", "entertainment"] },
  { symbol: "🎬", label: "Streaming", keywords: ["streaming", "movies", "tv", "entertainment"] },
  { symbol: "📚", label: "Education", keywords: ["education", "books", "learning", "school", "course"] },
  { symbol: "🎓", label: "Tuition", keywords: ["tuition", "school", "college", "education"] },
  { symbol: "🧑‍🏫", label: "Coaching", keywords: ["coaching", "training", "mentor", "education"] },
  { symbol: "🩺", label: "Medical", keywords: ["medical", "health", "doctor", "hospital"] },
  { symbol: "💊", label: "Pharmacy", keywords: ["pharmacy", "medicine", "health", "drugstore"] },
  { symbol: "🏋️", label: "Fitness", keywords: ["fitness", "gym", "sport", "health", "exercise"] },
  { symbol: "🧘", label: "Wellness", keywords: ["wellness", "yoga", "meditation", "relax"] },
  { symbol: "🎁", label: "Gifts", keywords: ["gift", "present", "surprise", "friend"] },
  { symbol: "🛍️", label: "Shopping", keywords: ["shopping", "fashion", "clothes", "bag"] },
  { symbol: "👗", label: "Clothing", keywords: ["clothing", "fashion", "outfit", "apparel"] },
  { symbol: "👟", label: "Shoes", keywords: ["shoes", "fashion", "clothes", "footwear"] },
  { symbol: "💄", label: "Beauty", keywords: ["beauty", "makeup", "cosmetics", "care"] },
  { symbol: "🧴", label: "Personal Care", keywords: ["personal", "care", "toiletries", "hygiene"] },
  { symbol: "🧒", label: "Kids", keywords: ["kids", "children", "family", "parenting"] },
  { symbol: "🐾", label: "Pets", keywords: ["pet", "animal", "vet", "food"] },
  { symbol: "🐶", label: "Dog", keywords: ["dog", "pet", "animal", "vet"] },
  { symbol: "🐱", label: "Cat", keywords: ["cat", "pet", "animal", "vet"] },
  { symbol: "🎢", label: "Entertainment", keywords: ["entertainment", "park", "activities", "fun"] },
  { symbol: "🎳", label: "Hobbies", keywords: ["hobby", "bowling", "craft", "activity", "fun"] },
  { symbol: "🎨", label: "Arts & Crafts", keywords: ["art", "craft", "creative", "painting"] },
  { symbol: "📸", label: "Photography", keywords: ["photo", "camera", "hobby", "media"] },
  { symbol: "📱", label: "Apps", keywords: ["app", "mobile", "software", "subscription", "digital"] },
  { symbol: "💼", label: "Salary", keywords: ["salary", "job", "work", "income", "paycheck"] },
  { symbol: "🧾", label: "Invoice", keywords: ["invoice", "billing", "client", "freelance"] },
  { symbol: "🧑‍💼", label: "Freelance", keywords: ["freelance", "consulting", "client", "work"] },
  { symbol: "💸", label: "Cash Out", keywords: ["cash", "withdrawal", "spending", "expense"] },
  { symbol: "🪙", label: "Coins", keywords: ["coins", "savings", "money", "cash"] },
  { symbol: "🏆", label: "Bonus", keywords: ["bonus", "reward", "prize", "income"] },
  { symbol: "🎯", label: "Goals", keywords: ["goal", "target", "saving", "plan"] },
  { symbol: "🏥", label: "Insurance", keywords: ["insurance", "health", "premium", "safety"] },
  { symbol: "🚨", label: "Emergency", keywords: ["emergency", "urgent", "unexpected"] },
  { symbol: "📞", label: "Communication", keywords: ["call", "communication", "phone", "contact"] },
  { symbol: "🌱", label: "Green Fund", keywords: ["green", "sustainable", "eco", "investment"] },
  { symbol: "🧠", label: "Learning", keywords: ["learning", "education", "brain", "course", "study"] },
  { symbol: "🤝", label: "Donations", keywords: ["donation", "charity", "give", "support"] },
  { symbol: "🙏", label: "Charity", keywords: ["charity", "donate", "give", "support"] },
  { symbol: "💐", label: "Celebrations", keywords: ["celebration", "flowers", "event", "gift"] },
  { symbol: "🏖️", label: "Beach Trip", keywords: ["beach", "travel", "holiday", "vacation"] },
  { symbol: "⛰️", label: "Adventure", keywords: ["adventure", "hiking", "trip", "travel"] },
  { symbol: "🔧", label: "Tools", keywords: ["tools", "hardware", "repair", "maintenance"] },
  { symbol: "🎟️", label: "Tickets", keywords: ["tickets", "event", "concert", "movie", "show"] },
  { symbol: "🎹", label: "Instruments", keywords: ["instrument", "music", "hobby", "piano"] },
  { symbol: "🖊️", label: "Office Supplies", keywords: ["office", "stationery", "work", "supplies"] },
  { symbol: "📮", label: "Postage", keywords: ["post", "shipping", "mail", "delivery"] },
  { symbol: "🚴", label: "Cycling", keywords: ["cycling", "bike", "sport", "fitness"] },
  { symbol: "⚽", label: "Sports", keywords: ["sport", "soccer", "fitness", "activity"] },
  { symbol: "🎲", label: "Board Games", keywords: ["board", "games", "fun", "tabletop"] },
  { symbol: "🎒", label: "Backpack", keywords: ["backpack", "school", "travel", "bag"] },
];
